### ISSUE TITLE
Button to set the target to max-size

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#3]
Create a button to set the spatial target to the max size of the video

**Comment by Drilio** [comment]
I implemented the button [there](https://github.com/SCENE-CE/mirador-annotation-editor/blob/5bca7813bd4bca115305f3e1d8798b9c3e8139aa/src/AnnotationCreation.js#L519) 

The function which handle the button click is [there](https://github.com/SCENE-CE/mirador-annotation-editor/blob/5bca7813bd4bca115305f3e1d8798b9c3e8139aa/src/AnnotationCreation.js#L230)

I have some questions : 

- Should I implement the button somewhere else ? 
- Should the function set the SpatialTarget to its initial position ?
- How Should I design the Button ? Should It be an MuiIcon ?

**Comment by daxid** [comment]
Partial answers : 

- The button is fine where it is, there should only be a "SPATIAL TARGET" section above (and thus a "TEMPORAL TARGET" instead of "TARGET")
- Yes the function set the SpatialTarget to its initial position "fulscreen" or fullframe in this case
- The button could be a fullscreen icon, maybe with a text before like "Fill the entire frame". We need to test stuff.

**Comment by geourjoa** [comment]
@daxid 

We need to precise this issue in view of new ui
