### ISSUE TITLE
Fix scale problem when exporting SVG from target selector

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#50]
When exporting the SVG from KONVA representing the target of the annotation, the svg width and height are the size of the Konva Stage (depending on the user screen and companion windows size)

The svg must be display with the height and width on the canvas

**Comment by geourjoa** [comment]
Search if React Konva can have the good params

https://github.com/dendrofen/react-konva-to-svg/blob/main/react-konva-to-svg/index.js

**Comment by daxid** [comment]
The branch https://github.com/SCENE-CE/mirador-annotation-editor/compare/master...86-stage-canvas-fix-scale contains a fix so that we now insert a valid SVG in the annotation (previously it was a json containing the SVG...)

However the SVG content is not what we expect. @d-flood if you have time I believe it would be nice to have a small SVG export proof of concept with Konvas, outside of the application if needed to simplify the matters.

**Comment by daxid** [comment]
The following shall be usefull:

https://www.npmjs.com/package/svgcanvas

**Comment by geourjoa** [comment]
Closed by #86
