### ISSUE TITLE
crash on workspace importation

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#98]
import workspace leads into this error : 

![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/a99c8bcd-8ad2-41b3-9ac9-838dcc5de9ab)

**Comment by Drilio** [comment]
This bug is present on mirador-annotations upstream and you can trigger it on : https://mirador-annotations.netlify.app/

**Comment by geourjoa** [comment]
The problem is double.

The export function don't export the adapter (a function) --> first problem
The missing value is config -> annotation -> adapter. So when the retrieve annotation function try to use the adapter, a TypeError error is thrown

The import don't check if the value is set --> second problem
In retrieve function in externalStorageAnnotationplugin,  I add the following checks. It can be improved 

```js
if (typeof config.annotation.adapter === 'string' && config.annotation.adapter === AnnotationAdapter.LOCAL_STORAGE) {
  config.annotation.adapter = (canvasId) => new LocalStorageAdapter(`localStorage://?canvasId=${canvasId}`);
}
if(typeof config.annotation.adapter === 'string' && config.annotation.adapter  === AnnotationAdapter.ANNOTOT) {
  const endpointUrl = 'http://127.0.0.1:3000/annotations';
  config.annotation.adapter = (canvasId) => new AnnototAdapter(canvasId, endpointUrl);
}
if (!config.annotation.adapter) {
  // Default adapter set to LocalStorageAdapter
  config.annotation.adapter = (canvasId) => new LocalStorageAdapter(`localStorage://?canvasId=${canvasId}`);
}
```

**Comment by geourjoa** [comment]
Code added in https://github.com/SCENE-CE/mirador-annotation-editor/tree/98-crash-on-workspace-importation
